apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: optisigns-assessment
resources:
- backend.yaml
- frontend.yaml
# Existing PostgreSQL, NFS, uploads PVC, gateway and Secrets are prerequisites.
images:
- digest: sha256:1cb81f6644b5a8ae660b80a93ecaba7a72297cb73710d8a03dbd7ef9787cd0e6
  name: demoooo.azurecr.io/optisigns-backend
  newName: demoooo.azurecr.io/optisigns-backend
  newTag: d112fb7
- digest: sha256:17864d7e4d2aa3c0c854bc3f6e9ea05c8077ed7b0c4a85d13534d509151bf1e1
  name: demoooo.azurecr.io/optisigns-frontend
  newName: demoooo.azurecr.io/optisigns-frontend
  newTag: d112fb7
