apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: optisigns-assessment
resources:
- backend.yaml
- frontend.yaml
# Existing PostgreSQL, NFS, uploads PVC, gateway and Secrets are prerequisites.
images:
- digest: sha256:551430e4d98aaf3b74c711cab2005ca87fc6b61d12556199ae34723bb175f9c8
  name: demoooo.azurecr.io/optisigns-backend
  newName: demoooo.azurecr.io/optisigns-backend
  newTag: 0d3ef78
- digest: sha256:3d3bb0c4dbb0acf1f8cab037f40a8f22d5b4fa880fc7641b3b558a68b9222045
  name: demoooo.azurecr.io/optisigns-frontend
  newName: demoooo.azurecr.io/optisigns-frontend
  newTag: 149b8cf
