import assert from 'node:assert/strict';
import { authConfig, installAuth } from './dist/auth.js';
import { db } from './dist/db.js';
assert.equal(authConfig({}), null);
assert.equal(authConfig({ AUTH_ENABLED: 'false' }), null);
assert.throws(() => authConfig({ AUTH_ENABLED: 'yes' }));
assert.throws(() => authConfig({ AUTH_ENABLED: 'true' }));
const env = { AUTH_ENABLED: 'true', AUTH_USERNAME: 'test-reviewer', AUTH_PASSWORD_HASH: `${'a'.repeat(32)}:${'b'.repeat(128)}`, PUBLIC_ORIGIN: 'https://review.example.test' };
assert.equal(authConfig(env).origin, env.PUBLIC_ORIGIN);
assert.throws(() => authConfig({ ...env, PUBLIC_ORIGIN: 'http://review.example.test' }));
assert.throws(() => authConfig({ ...env, PUBLIC_ORIGIN: `${env.PUBLIC_ORIGIN}/path` }));
assert.throws(() => authConfig({ ...env, AUTH_PASSWORD_HASH: 'invalid' }));
const original = process.env.AUTH_ENABLED;
delete process.env.AUTH_ENABLED;
let route;
await installAuth({ get(path, handler) { route = path; handler({}, { set() { return this; }, json(body) { assert.deepEqual(body, { enabled: false }); } }); } });
assert.equal(route, '/auth/session');
if (original !== undefined) process.env.AUTH_ENABLED = original;
await db.end();
console.log('PASS auth configuration rejects unsafe settings; local mode needs no database session');
