apiVersion: v1
kind: Pod
metadata:
  name: nfs-writer
  namespace: optisigns-assessment
spec:
  automountServiceAccountToken: false
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: test
      image: busybox:1.37.0
      command: [sh, -c, 'sleep 86400']
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop: [ALL]
      resources:
        requests: {cpu: 10m, memory: 8Mi}
        limits: {cpu: 100m, memory: 32Mi}
      volumeMounts:
        - name: uploads
          mountPath: /uploads
  volumes:
    - name: uploads
      persistentVolumeClaim:
        claimName: uploads
---
apiVersion: v1
kind: Pod
metadata:
  name: nfs-reader
  namespace: optisigns-assessment
spec:
  automountServiceAccountToken: false
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: test
      image: busybox:1.37.0
      command: [sh, -c, 'sleep 86400']
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop: [ALL]
      resources:
        requests: {cpu: 10m, memory: 8Mi}
        limits: {cpu: 100m, memory: 32Mi}
      volumeMounts:
        - name: uploads
          mountPath: /uploads
          readOnly: true
  volumes:
    - name: uploads
      persistentVolumeClaim:
        claimName: uploads
